version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$REGISTRY_URI/backend-repo
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY_URI
  build:
    commands:
      - echo Building DevBank backend image...
      - docker build -t backend-repo .
      - docker tag backend-repo:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing image to Amazon ECR...
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"devbank-backend","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json